version: '2.4'
services:
  web:
    image: nfqlt/apache2438-fastcgi
    ports:
      - '10.24.1.65:80:80'
    links:
      - fastcgi
    volumes:
      - './src:/home/project/src'
    environment:
      APACHE_DOCUMENTROOT: /home/project/src/public
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_ENABLE_APACHE_MODULES: rewrite


  fastcgi:
    image: nfqlt/php73-fpm
    links:
      - mysql
    volumes:
      - './src:/home/project/src'
      - './conf.d/php.ini:/etc/php/7.3/fpm/conf.d/99-php-custom.ini:ro'
      - './xdebug.ini:/etc/php/7.3/mods-available/xdebug.ini:ro'
    environment:
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_ENABLE_PHP_MODULES: 'mysqlnd curl json pdo pdo_mysql mcrypt ctype tokenizer simplexml intl opcache mbstring xml zip dom xmlwriter xmlreader iconv gd xdebug fileinfo'


  mysql:
    image: 'mysql:5.7'
    ports:
      - '10.24.1.65:3306:3306'
    volumes_from:
      - 'service:mysqlVol:rw'


  mysqlVol:
    image: nfqlt/mysql57-data
    volumes:
      - /var/lib/mysql


  dev:
    image: nfqlt/php73-vscode
    shm_size: 256M
    ports:
      - '10.24.1.65:22:22'
    links:
      - mysql
    volumes_from:
      - service:node:rw
    volumes:
      - './conf.d/php.ini:/etc/php/7.3/cli/conf.d/99-php-custom.ini:ro'
      - './src:/home/project/src'
      - '/home/project/.ssh:/home/project/.ssh'
      - '/etc/ssh:/etc/ssh'
      - '/etc/gitconfig:/etc/gitconfig'
      - '/etc/environment:/etc/environment-vm:ro'
      - '/vagrant/bash_custom:/home/project/.bash_custom'
      - '/home/project/.Xauthority:/home/project/.Xauthority'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    environment:
      DISPLAY: $DISPLAY
      NFQ_ENABLE_PHP_MODULES: 'mysqlnd curl json pdo pdo_mysql mcrypt ctype tokenizer simplexml intl opcache mbstring xml zip dom xmlwriter xmlreader iconv gd xdebug fileinfo'
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_PROJECT_GIT_REPO: 'https://github.com/makerspacelt/tools.git'
      NFQ_PROJECT_GIT_BRANCH: develop
      NFQ_INIT_SCRIPT: tools/docker/develop_init.sh
      NFQ_REMOTE_TOOL_NODE: >
        /usr/bin/yarn
        /usr/bin/node
        /usr/bin/grunt


  mail:
    image: nfqlt/mailhog
    ports:
      - '10.24.1.65:1080:80'
      - '10.24.1.65:25:25'


  linker:
    image: nfqlt/linker18ce
    volumes:
      - '/run/docker.sock:/run/docker.sock'


  node:
    image: nfqlt/node12
    volumes:
      - './src:/home/project/src'
      - /tmp


volumes: {  }
networks:
  default:
    ipam:
      config:
        -
          subnet: 10.24.1.65/28

